services:
  postgres:
    image: postgres:15-alpine
    container_name: libraryos-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:

      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - libraryos-network

  catalog_fpm:
    build:
      context: ./services/catalog-service
      dockerfile: Dockerfile
    container_name: catalog-service
    environment:
      APP_ENV: local
      APP_KEY: base64:FzVOJL+8zHcfvjvrMMzjIchGcHk6AlOCBrxsbZLvn9k=
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: catalog_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
   
    depends_on:
      - postgres
    networks:
      - libraryos-network
    
  catalog_nginx:
    build:
      context: ./services/catalog-service
      dockerfile: docker/Dockerfile.nginx
    container_name: catalog-nginx
    ports:
      - "8001:80"
    depends_on:
      - catalog_fpm
    networks:
      - libraryos-network

networks:
      libraryos-network:
        driver: bridge
volumes:
  postgres_data:


